# Placeholder accelerate configuration.
# Generate a tailored config with `accelerate config` and replace this file.
compute_environment: LOCAL_MACHINE
distributed_type: NO
mixed_precision: bf16
num_processes: 1
machine_rank: 0
main_process_ip: null
main_process_port: null
num_machines: 1
gpu_ids: "all"
downcast_bf16: "no"
