_wandb:
    value:
        cli_version: 0.22.2
        e:
            q22geb18yrknvjyizjfe8zfi0x6620n7:
                args:
                    - train-model
                    - --config
                    - /content/drive/MyDrive/colab/drawing-agent/configs/training.sdxl-qlora.yaml
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "253055008768"
                        used: "52728893440"
                email: admin@phaethon.llc
                executable: /usr/bin/python3
                git:
                    commit: 119c309fdfccf527d51e3fdb09cc84bb24cfc694
                    remote: https://github.com/aonanj/drawing-agent.git
                host: 5dc0749c2ab2
                memory:
                    total: "179370496000"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: -m src.tuning.cli
                python: CPython 3.12.12
                root: /content/drive/MyDrive/colab/drawing-agent
                startedAt: "2025-10-31T00:36:10.931381Z"
                writerId: q22geb18yrknvjyizjfe8zfi0x6620n7
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 53
                - 71
                - 83
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 53
                - 71
                - 83
                - 98
                - 105
            "3":
                - 61
            "4": 3.12.12
            "5": 0.22.2
            "6": 4.57.1
            "12": 0.22.2
            "13": linux-x86_64
data:
    value:
        control_column: control
        dataset_config: configs/dataset.figures.yaml
        image_column: image
        prompt_column: prompt
        train_split: train
        validation_split: validation
evaluation:
    value:
        num_validation_images: 8
        steps: 800
        use_reference_images: true
hardware:
    value:
        enable_flash_attention: false
        gradient_checkpointing: true
        mixed_precision: bf16
        use_cpu_offload: false
logging:
    value:
        gradient_checkpointing: true
        logging_steps: 10
        report_to: wandb
model:
    value:
        cache_dir: .cache/huggingface
        pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
        revision: fp16
        variant: fp16
optimizer:
    value:
        betas:
            - 0.9
            - 0.999
        learning_rate: 0.0001
        lr_scheduler: cosine_with_restarts
        num_cycles: 1
        type: adamw_8bit
        warmup_steps: 100
        weight_decay: 0.01
output_dir:
    value: outputs/sdxl-qlora-run-3
project_name:
    value: drawing-agent
qlora:
    value:
        alpha: 16
        compute_dtype: bf16
        dropout: 0.05
        quantization_bits: 4
        r: 32
        target_modules:
            - to_k
            - to_q
            - to_v
            - to_out.0
        use_gradient_checkpointing: true
resume_from_checkpoint:
    value:
        enabled: false
        path: outputs/sdxl-qlora-run-
        start_step: 0
run_name:
    value: sdxl-qlora-run-3
seed:
    value: 42
training:
    value:
        checkpointing_steps: 500
        enable_xformers_memory_efficient_attention: true
        gradient_accumulation_steps: 8
        gradient_checkpointing: true
        mixed_precision: bf16
        num_train_epochs: 3
        resolution: 1024
        save_adapters_only: true
        train_batch_size: 1
