# Quick test configuration for SDXL QLoRA training
seed: 42
project_name: drawing-agent-test
run_name: sdxl-qlora-test
output_dir: outputs/test

model:
  pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
  revision: fp16
  variant: fp16
  cache_dir: .cache/huggingface

qlora:
  r: 8  # Smaller rank for faster testing
  alpha: 8
  dropout: 0.05
  target_modules:
    - to_k
    - to_q
    - to_v
    - to_out.0
  quantization_bits: 4
  compute_dtype: bf16
  use_gradient_checkpointing: true

training:
  resolution: 1024
  train_batch_size: 1
  gradient_accumulation_steps: 2
  max_train_steps: 5  # Just 5 steps for testing
  checkpointing_steps: 5
  save_adapters_only: true
  mixed_precision: bf16
  gradient_checkpointing: true
  enable_xformers_memory_efficient_attention: true

optimizer:
  type: adamw_8bit
  learning_rate: 1.0e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01
  lr_scheduler: constant
  num_cycles: 1
  warmup_steps: 0

data:
  dataset_config: configs/dataset.figures.yaml
  train_split: train
  validation_split: validation
  image_column: image
  prompt_column: prompt
  control_column: control

logging:
  report_to: wandb
  logging_steps: 1
  gradient_checkpointing: true

hardware:
  mixed_precision: bf16
  use_cpu_offload: false
  gradient_checkpointing: true
  enable_flash_attention: false

evaluation:
  steps: 10
  num_validation_images: 4
  use_reference_images: true
